---
- name: Configure Database servers
  hosts: databases
  become: true

  tasks:
    # Install postgresql-server & Setup postgresql & Start and enable postgresql service
    - name: Install postgresql-server
      ansible.builtin.package:
        name: postgresql-server
        state: present

    - name: Setup postgresql
      ansible.builtin.command: /usr/pgsql-12/bin/postgresql-setup initdb
      args:
        creates: /var/lib/pgsql/data/postgresql.conf

    - name: Start and enable postgresql service
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true

