---
# Chronyのインストール
- name: Install chrony
  ansible.builtin.package:
    name: chrony
    state: present

# Chronydサービスを起動し、自動起動を有効化
- name: Start and enabled Chronyd
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true

# タイムゾーンをAsia/Tokyoに変更
- name: Set timezone to Asia/Tokyo
  community.general.timezone:
    name: Asia/Tokyo

# ここは削除せずに残して下さい
- name: Set fact hostname
  ansible.builtin.set_fact:
    hostname: "handson.ibmcloud.com"

# ホスト名変更(セットする値はhostname変数を利用)
- name: Set hostname using vars hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

# プロンプトの変更(prompt.sh.j2を/etc/profile.d/にコピー
- name: Copy prompt.sh.j2 to /etc/profile.d
  ansible.builtin.template:
    src: prompt.sh.j2
    dest: /etc/profile.d/prompt.sh
    mode: '0644'

# langpacks-jaのインストール
- name: Install langpacks-ja
  ansible.builtin.package:
    name: langpacks-ja
    state: present

# ロケールステータスを取得(localectlコマンドを利用)
- name: Get locale status using localectl command
  ansible.builtin.command: localectl status
  register: locale_status
  changed_when: false

# 上記のリストに"LANG=ja_JP.utf8"がなければロケールをja_JP.utf8に設定(localectlコマンドを利用)
- name: Ensure locale is set to "ja_JP.utf8" if not already configured
  ansible.builtin.command: localectl set-locale LANG=ja_JP.utf8
  when: '"ja_JP.utf8" not in locale_status.stdout'
