# Chronyのインストール

# Chronydサービスを起動し、自動起動を有効化

# タイムゾーンをAsia/Tokyoに変更

# ここは削除せずに残して下さい
- name: Set fact hostname
  ansible.builtin.set_fact:
    hostname: "handson.ibmcloud.com"

# ホスト名変更(セットする値はhostname変数を利用)

# プロンプトの変更(prompt.sh.j2を/etc/profile.d/にコピー

# langpacks-jaのインストール

# ロケールステータスを取得(localectlコマンドを利用)

# 上記のリストに"LANG=ja_JP.utf8"がなければロケールをja_JP.utf8に設定(localectlコマンドを利用)
